services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: csvdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  app:
    build: .
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: csvdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      NEXT_TELEMETRY_DISABLED: 1
      NODE_ENV: production
    depends_on:
      - postgres
    ports:
      - "3000:3000"
volumes:
  pgdata:
